/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BirthdayPartiesRouteImport } from './routes/birthday-parties'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateEventsRouteImport } from './routes/corporate-events'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PricingRouteImport } from './routes/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayPartiesRoute = BirthdayPartiesRouteImport.update({
  id: '/birthday-parties',
  path: '/birthday-parties',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateEventsRoute = CorporateEventsRouteImport.update({
  id: '/corporate-events',
  path: '/corporate-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birthday-parties': typeof BirthdayPartiesRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birthday-parties': typeof BirthdayPartiesRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birthday-parties': typeof BirthdayPartiesRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-events': typeof CorporateEventsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/birthday-parties'
    | '/book'
    | '/contact'
    | '/corporate-events'
    | '/experiences'
    | '/faq'
    | '/franchise'
    | '/gallery'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/birthday-parties'
    | '/book'
    | '/contact'
    | '/corporate-events'
    | '/experiences'
    | '/faq'
    | '/franchise'
    | '/gallery'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/birthday-parties'
    | '/book'
    | '/contact'
    | '/corporate-events'
    | '/experiences'
    | '/faq'
    | '/franchise'
    | '/gallery'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BirthdayPartiesRoute: typeof BirthdayPartiesRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  CorporateEventsRoute: typeof CorporateEventsRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  FranchiseRoute: typeof FranchiseRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-parties': {
      id: '/birthday-parties'
      path: '/birthday-parties'
      fullPath: '/birthday-parties'
      preLoaderRoute: typeof BirthdayPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-events': {
      id: '/corporate-events'
      path: '/corporate-events'
      fullPath: '/corporate-events'
      preLoaderRoute: typeof CorporateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BirthdayPartiesRoute: BirthdayPartiesRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  CorporateEventsRoute: CorporateEventsRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  FranchiseRoute: FranchiseRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
